### ISSUE TITLE
When using the auto-schema-registry, the nullable field did not actually register as nullable there 

### ISSUE THREAD

**Issue by lixiandai** [ch-robinson/dotnet-avro#88] opened 2020-07-02 20:43 UTC
This is the field we defined in our .avsc 
 {
      "name": "test",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "test nullable string field"
},

After using producer with the Chr.Avro.Confluent auto registry turn on, we saw the registered schema looks like this 
{\"name\":\"test\",\"type\":\"string\"}
It seems omit the null type there.

**Comment by dstelljes** [comment] 2020-07-05 23:22
Your .avsc file won't have any effect in that situation, since the schema that Chr.Avro.Confluent registers is generated by reflecting your .NET types. If you want to use the contents of the .avsc file instead of a generated schema, don't use auto registration; instead, read the file and use the Schema Registry client to register it.

Alternatively, if you want Chr.Avro to use .NET's nullable semantics (i.e., any reference types can have a null value) when generating schemas, you can provide a custom schema builder:

```csharp
using Chr.Avro.Abstract;
using Chr.Avro.Confluent;
using Chr.Avro.Resolution;
using Confluent.Kafka;
using Confluent.SchemaRegistry;

var registry = new CachedSchemaRegistryClient(new SchemaRegistryConfig { ... });

var typeResolver = new ReflectionResolver(
  resolveReferenceTypesAsNullable: true // this is the important line
);

var schemaBuilder = new SchemaBuilder(typeResolver: typeResolver);
var serializerBuilder = new SchemaRegistrySerializerBuilder(registry, schemaBuilder: schemaBuilder)
var producerBuilder = new ProducerBuilder<Ignore, SomeValue>();

await builder.SetAvroValueSerializer(serializerBuilder, "test-subject", registerAutomatically: AutomaticRegistrationBehavior.Always);
```

**Comment by dstelljes** [comment] 2020-07-17 14:14
Closing this out; feel free to reopen if you feel the issue isn't resolved.

**Closed by dstelljes** 2020-07-17 14:14 UTC
